### ISSUE TITLE
exiftool

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/passbypromised#7]

**Comment by Ironholds** [comment]
http://www.sno.phy.queensu.ca/~phil/exiftool/

**Comment by jhollist** [comment]
@Ironholds Happy to help with this if I can.  I just an ecologist hacker so my c++ skills are non-existent.  Could always help out with documentation and some to the R stuff.  Let me know and thanks for thinking about this.

**Comment by Ironholds** [comment]
No problem! Totally happy to work on it. At the moment picking the backend is the problem; despite the theoretical support for .tiff files, most libs seem JPEG-only. Which...seems weird (they shouldn't be storing .exif in different formats, surely?) What do you think of http://libexif.sourceforge.net/ ?

**Comment by Ironholds** [comment]
Done!
